version: '3.8'
services:
  db:
    container_name: nestjs_microservices_mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nestjs_microservices_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  mysql_db:
